export const CREATE_BOOK_INIT = "CREATE_BOOK_INIT";
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS";
export const CREATE_BOOK_FAILED = "CREATE_BOOK_FAILED";

export const SET_BOOK = "SET_BOOK";
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS";
export const GET_BOOK_FAILED = "GET_BOOK_FAILED";

export const GET_BOOKS_INIT = "GET_BOOKS_INIT";
export const GET_BOOKS_SUCCESS = "GET_BOOKS_SUCCESS";
export const GET_BOOKS_FAILED = "GET_BOOKS_FAILED";

export const UPDATE_BOOK_INIT = "UPDATE_BOOK_INIT";
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS";
export const UPDATE_BOOK_FAILED = "UPDATE_BOOK_FAILED";

export const DELETE_BOOK_INIT = "DELETE_BOOK_INIT";
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS";
export const DELETE_BOOK_FAILED = "DELETE_BOOK_FAILED";

export const GET_ERRORS = "GET_ERRORS";
